import SummaryBot from './summary-bot';

let article = "At least 5 people died after a powerful storm pummeled Southern California on Friday night, flooding numerous roadways in Los Angeles and San Diego.\n\nRescuers on Saturday in the community of Thousand Oaks found the body of a young man in his 20s who had been swept away by swift-moving waters, the Ventura County Sheriff's Office said.\n\nEarlier, in the Sherman Oaks neighborhood of Los Angeles, a falling tree brought down power lines and hit a car on Friday night. A 55-year-old man was electrocuted and pronounced dead at a hospital, police and fire officials said.\n\nTwo others died in separate car accidents on Interstate 15 in San Diego amid heavy rain. And a motorist was found dead in a fully submerged vehicle in Victorville in San Bernardino County, officials said.\n\n";

article += "In the Studio City neighborhood of Los Angeles, two cars plunged into a massive sinkhole. At least one person was trapped when the first vehicle fell into the hole until rescue crews were able to pull the woman out of the car. She was transported to the hospital for injuries and her condition is unknown, according to ABC owned-and-operated television station KABC.\n\n";

article += "Minutes later, the sinkhole swallowed a second vehicle, which was unoccupied at the time, KABC reported.\n\nThe massive Pacific storm swept into Southern California on Friday morning, bringing torrential rain and gusting winds to the region while also spreading precipitation north into the San Joaquin Valley and up to San Francisco.\n\nFlash flood watches were in effect for Los Angeles, Ventura and Santa Barbara counties from Friday morning through Saturday morning. Forecasters said the weather system could be the strongest to pelt the region in years, if not decades.\n\n'The storm looks to be the strongest storm to hit southwest California this season,' the National Weather Service office for the Los Angeles region wrote. 'It is likely the strongest within the last six years and possibly even as far back as December 2004 or January 1995.'\n\n";

article +="The storm was expected to generate a total of 3 to 6 inches of rain in Los Angeles County beaches and valleys and 5 to 10 inches of rain in south-facing foothills and coastal mountain slopes, according to the National Weather Service.\n\nWith soil already soaked from significant rainfall this winter, forecasters warned of the potential for flash floods and debris flows, especially near areas stripped bare by wildfires. Precautionary evacuations were requested in some neighborhoods.\n\nAs of 10 p.m. local time on Friday, more than 78,000 customers were affected by power outages in the Los Angeles area alone, where hundreds of trees and dozens of power lines had toppled, according to the Los Angeles Department of Water and Power.\n\n";

article += "Winds gusting to 70 mph or more lashed parts of the region, while heavy downpours turned creeks and rivers into brown torrents and loosened mud from hillsides left barren by recent wildfires. Several stretches of freeways and highways were shut down from floods.\n\nRecord-breaking rainfall was recorded across southwestern California on Friday. For instance, Santa Barbara Airport saw 4.16 inches of rain, beating the record of 2.08 inches set in 1980, according to the National Weather Service.\n\nBy Saturday morning, isolated locations had received up to 10 inches of rain. Parts of Ventura and San Bernardino counties had received over 8 inches of rain. The city of Los Angeles had received at least 2 inches of rain, according to ABC News meteorologists tracking the storm.\n\n";

article += "Heavy rain and high winds lingered over much of Southern California on Saturday morning. The rain is expected to move east as the day goes on, with the chance for scattered pockets of heavier showers in Los Angeles and San Diego. Drier weather is expected to move in Saturday afternoon and evening.\n\nMeanwhile, a new Pacific storm will take aim at Central California's coastline on Sunday.\n\n'The worst is over for Los Angeles this morning,' said ABC News meteorologist Daniel Manzo. 'Next storm is on the way late Sunday and will focus on Central and Northern California.'\n\nThe new storm could dump an additional 3 to 4 inches on Northern California, according to Manzo.\n\n'This is another dangerous situation developing due to swollen water ways and saturated ground,' Manzo said.";


let summary = SummaryBot(article, 5);
console.log(JSON.stringify(summary, null, 4));
console.log(summary.text);
console.log(`\n We were able to shorten the article by: ${summary.percentReduction}%`);
